database:
  driver: H2 # Can be H2, YAML or MySQL (not case-sensitive)
  mysql:
    hostname: "localhost"
    port: 3306
    database: "premiumtags"
    username: "root"
    password: ""
placeholders:
  tag_selection_inventory_title: "&6Select a tag"