name: PremiumTags
version: '${version}'
author: Adrigamer2950
main: me.adrigamer2950.premiumtags.PremiumTags
api-version: '1.14'
website: https://github.com/Adrigamer2950/PremiumTags
folia-supported: true

libraries:
  - com.h2database:h2:2.1.210

depend:
  - AdriAPI

softdepend:
  - PlaceholderAPI

commands:
  tags:
    usage: /tags
  premiumtags:
    aliases:
      - pt
    usage: /pt help