name: PremiumTags
version: '${version}'
author: Adrigamer2950
main: me.adrigamer2950.premiumtags.PremiumTags
api-version: '1.18'
website: https://github.com/Adrigamer2950/PremiumTags
folia-supported: true

depend:
  - AdriAPI

softdepend:
  - PlaceholderAPI

commands:
  tags:
    usage: /tags help