name: PremiumTags
version: '${version}'
author: Adrigamer2950
main: me.adrigamer2950.premiumtags.PremiumTags
api-version: '1.18'
website: https://github.com/Adrigamer2950/AdriTags
website: https://github.com/Adrigamer2950/PremiumTags

depend:
  - AdriAPI

commands:
  adritags:
    usage: /adritags help
    aliases: tags